<a href="https://colab.research.google.com/github/Eugenefut19/Pytorch-Tutorial/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors Operations**

In [30]:
import torch
import numpy as np

In [33]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [40]:
#Reshape if we don't know the number ot items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
my_torch2 =my_torch2.reshape(3,-1)
my_torch2


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [42]:
my_torch3= torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
my_torch4=my_torch3.view(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [44]:
my_torch5= torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
my_torch6= my_torch5.view(2,5)
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [48]:
my_torch5[1]=4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [49]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [52]:
#Slices
my_torch7= torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
#grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

my_torch8[:, -1]

tensor([1, 3, 5, 7, 9])

In [66]:
my_torch8[:, 0]

tensor([0, 2, 4, 6, 8])