<a href="https://colab.research.google.com/github/Eugenefut19/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors**

In [10]:
import torch
import numpy as np

**Lists**

In [13]:
my_list =[[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**Numpy** **Array**

In [23]:
np1 = np.random.rand(3,4)
np1.dtype

np1

array([[0.35088432, 0.87118171, 0.0734833 , 0.01784373],
       [0.69607113, 0.78716651, 0.9987686 , 0.56192195],
       [0.03876427, 0.35615289, 0.81923579, 0.63601017]])

**Tensor**

In [28]:
tensor_2d= torch.randn(3,4)
tensor_2d

tensor([[-1.9469, -0.3999, -0.0268, -0.4057],
        [-0.5388, -0.8295, -0.7872,  0.6735],
        [-0.2333, -0.8194,  1.1798, -1.1522]])

In [24]:
tensor_3d= torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [26]:
## Create tensor out of numpy array
my_tensor= torch.tensor(np1)
my_tensor.dtype

torch.float64